apiVersion: v2
name: poi-project
description: A Helm chart for the POI project.
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: metrics-server
    version: "3.12.1"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
